## Generate random values for hyper-paramter tuning

In [3]:
from numpy import random

#### Hidden Size

In [59]:
hidden_sizes = random.randint(3,300,2)
hidden_sizes

array([236, 119])

#### Weight Decay

In [68]:
decay_weights = random.uniform(1e-5,1e-4,2)
decay_weights

array([  1.14309620e-05,   7.51516239e-05])

#### Learning Rate

In [80]:
learning_rates = random.uniform(5e-4,5e-3,2)
learning_rates

array([ 0.00374878,  0.00086602])

#### Dropout

In [85]:
dropouts = random.uniform(0,.5,2)
dropouts

array([ 0.00905095,  0.49439426])

In [86]:
print('Hidden size:',hidden_sizes,'\nDecay Weights:',decay_weights,\
      '\nLearning Rates:',learning_rates,'\nDropout:',dropouts)

Hidden size: [236 119] 
Decay Weights: [  1.14309620e-05   7.51516239e-05] 
Learning Rates: [ 0.00374878  0.00086602] 
Dropout: [ 0.00905095  0.49439426]
