## Generate random values for hyper-paramter tuning

In [1]:
import numpy as np
from numpy import random

From http://mfile.narotama.ac.id/files/Umum/Jurnal%20MIT/Random%20search%20for%20hyper-parameter%20optimization.pdf:

"We will use the phrase drawn geometrically from A to B for 0 < A < B to mean drawing uniformly in the log domain
between log(A) and log(B), exponentiating to get a number between A and B, and then rounding to the nearest integer.
The phrase drawn exponentially means the same thing but without rounding."

#### Hidden Size

In [2]:
A = 50
B = 500
hidden_sizes = np.round(np.exp(random.uniform(np.log(A),np.log(B),3)))
hidden_sizes

array([  51.,  111.,  221.])

#### Weight Decay

In [3]:
A = 5.0e-5
B = 5.0e-3
decay_weights = np.exp(random.uniform(np.log(A),np.log(B),3))
decay_weights

array([  2.98737489e-03,   7.45330507e-05,   1.28245922e-03])

#### Learning Rate

In [4]:
A = 5e-5
B = 5e-3
learning_rates = np.exp(random.uniform(np.log(A),np.log(B),3))
learning_rates

array([  6.01289453e-05,   5.95348191e-04,   5.05725442e-04])

#### Dropout

In [5]:
A = .01
B = 0.3
dropouts = np.exp(random.uniform(np.log(A),np.log(B),3))
dropouts

array([ 0.0143747 ,  0.25367569,  0.10096003])

In [6]:
print('Hidden size:',hidden_sizes,'\nDecay Weights:',decay_weights,\
      '\nLearning Rates:',learning_rates,'\nDropout:',dropouts)

Hidden size: [  51.  111.  221.] 
Decay Weights: [  2.98737489e-03   7.45330507e-05   1.28245922e-03] 
Learning Rates: [  6.01289453e-05   5.95348191e-04   5.05725442e-04] 
Dropout: [ 0.0143747   0.25367569  0.10096003]
