## Generate random values for hyper-paramter tuning

In [13]:
import numpy as np
from numpy import random

From http://mfile.narotama.ac.id/files/Umum/Jurnal%20MIT/Random%20search%20for%20hyper-parameter%20optimization.pdf:

"We will use the phrase drawn geometrically from A to B for 0 < A < B to mean drawing uniformly in the log domain
between log(A) and log(B), exponentiating to get a number between A and B, and then rounding to the nearest integer.
The phrase drawn exponentially means the same thing but without rounding."

#### Hidden Size

In [29]:
A = 18
B = 1024
hidden_sizes = np.round(np.exp(random.uniform(np.log(A),np.log(B),3)))
hidden_sizes

array([ 477.,  345.,   67.])

#### Weight Decay

In [39]:
A = 5.0e-5
B = 5.0e-3
decay_weights = np.exp(random.uniform(np.log(A),np.log(B),3))
decay_weights

array([ 0.00080853,  0.00029232,  0.00317727])

#### Learning Rate

In [38]:
A = 5e-5
B = 5e-3
learning_rates = np.exp(random.uniform(np.log(A),np.log(B),3))
learning_rates

array([ 0.00105849,  0.00010868,  0.00030144])

#### Dropout

In [44]:
A = .01
B = 0.3
dropouts = np.exp(random.uniform(np.log(A),np.log(B),3))
dropouts

array([ 0.07051246,  0.15142926,  0.0594544 ])

In [45]:
print('Hidden size:',hidden_sizes,'\nDecay Weights:',decay_weights,\
      '\nLearning Rates:',learning_rates,'\nDropout:',dropouts)

Hidden size: [ 477.  345.   67.] 
Decay Weights: [ 0.00080853  0.00029232  0.00317727] 
Learning Rates: [ 0.00105849  0.00010868  0.00030144] 
Dropout: [ 0.07051246  0.15142926  0.0594544 ]
